### ISSUE TITLE
Documentation Usability

### ISSUE THREAD

**Issue by TylerL-uxai** [primaryobjects/strips#1]
This is fascinating! Could you please elaborate the anomaly solution more? I don't understand:

What the x represents
What makes an anomaly

Thank you!

**Comment by primaryobjects** [comment]
The [Sussman Anomaly](https://github.com/primaryobjects/strips#sussman-anomaly-solution) is a type of block-stacking problem ([illustration](http://en.wikipedia.org/wiki/Sussman_Anomaly)), where you have two competing goals. One goal is to stack block A on top of block B. The other is to stack block B on top of block C. Early AI planning algorithms couldn't separate the goals and would fail to solve this problem. The STRIPS approach easily solves this.

In the solution output, 'x' is the name of the table, and 'a', 'b', 'c' are the names of the blocks. Thanks.
