### ISSUE TITLE
Approaches to creating a program

### ISSUE THREAD

**Issue by TylerL-uxai** [primaryobjects/strips#2]
I'm really interested in AI and am on lecture 5 of this series http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-034-artificial-intelligence-fall-2010/lecture-videos/

I'm thinking it'd be fun to try a stock market AI using node.js. Can you guys give me some high level concepts that the program would probably use to accomplish the goal of predicting stocks performance?

I was thinking you could do market size based on google searches and then look at where the search trend is expected to head...

Also, there's something called "sentiment analysis."

Could you guys give me some guidance and direction here? I feel like a breadth first search, going in every direction.

**Comment by primaryobjects** [comment]
You could start with using a linear regression on historical data to find trends. You may also want to check out SVMs and neural networks for predicting future action. [Here](https://github.com/primaryobjects/nnsorting) is an example of using a neural network in node.js. Sentiment analysis classification can also be done with SVMs and neural networks. Something similar to [this](http://www.primaryobjects.com/CMS/Article158), but classifying on positive or negative. Hope this helps.
