### ISSUE TITLE
Is graph.js working?

### ISSUE THREAD

**Issue by jorgearuv** [primaryobjects/strips#3]
Hey,  I'm trying to run the graph.js example. The documentation only says I have to run `node --harmony graph` but it throw errors after installing the npm dependecies. ¿Could you please explain me if I'm doing something wrong or what dependencies versions do I have to have to run this example correctly?

Thanks in advance.

**Comment by primaryobjects** [comment]
Ok, I've [fixed](https://github.com/primaryobjects/strips/commit/a560aca2bfcb3330a24556904583443a0bcc058c) it. d3.js has been set to version 3.*. Also, the code that saves to an SVG had to be tweaked slightly. It's working now! Thanks. :)
