### ISSUE TITLE
The function buildParser won't work because it has a differant name now

### ISSUE THREAD

**Issue by lorenzoverde** [primaryobjects/strips#4]
If you try to install and run strips today you'll also get the latest version of pegjs; they've chenged the name of the function "peg.buildParser" to "peg.generate", so you'll have to change it manually in strips.js:32 for the whole thing to work without errors.

**Comment by primaryobjects** [comment]
Thanks! Can you send a pull request?

**Comment by primaryobjects** [comment]
Thank you! Resolved via https://github.com/primaryobjects/strips/commit/d77d2ada3cd6d7d0601cb8d7a43795ac1a045638
