### ISSUE TITLE
No instructions for running 

### ISSUE THREAD

**Issue by swarupmohalik** [primaryobjects/strips#6]
It would be great for beginners like me to have some instructions on how to run the system.

**Comment by primaryobjects** [comment]
It's there! :) Documentation is available for [using strips](https://github.com/primaryobjects/strips/blob/master/strips/Readme.md) and also on [npm](https://www.npmjs.com/package/strips).

Even better, there is a great tutorial, [Artificial Intelligence Planning with STRIPS, A Gentle Introduction](http://www.primaryobjects.com/2015/11/06/artificial-intelligence-planning-with-strips-a-gentle-introduction/).

Hope that helps!
