### ISSUE TITLE
Name supported PDDL specification

### ISSUE THREAD

**Issue by padmalcom** [primaryobjects/strips#8]
Hi, your library looks great. Can you please tell us what PDDL specification you support (1.2, 2.1, 3.1 ...?).

Thank you!

**Comment by primaryobjects** [comment]
Please see the [documentation](https://github.com/primaryobjects/strips/blob/master/strips/Readme.md) for details on usage and example PDDL programs.

Regarding the version of PDDL used, please see the [grammar](https://github.com/primaryobjects/strips/tree/master/strips/grammar) parser. Thanks.
