### ISSUE TITLE
DeMorgan's Law in preconditions

### ISSUE THREAD

**Issue by Tushn** [primaryobjects/strips#9]
Hello,

I'm trying to study PDDL and planning technologies. I was trying to use your example "magicworld" and I could not write in domain a new definition for "move". My idea for "move" is a new precondition using "OR" operator for border, like:

to change
`:precondition (and (at ?p ?l1) (border ?l1 ?l2) (not (guarded ?l2)))`
for
`:precondition (and (at ?p ?l1) (or (border ?l1 ?l2) (border ?l2 ?l1)) (not (guarded ?l2)))`

However, I did not find anything about "OR" operator in PDDL yet. Then, I thought in DeMorgan's Law, and I tried:
`
:precondition (and (at ?p ?l1) (not (and (not (border ?l1 ?l2) ) (not (border ?l2 ?l1) ))) (not (guarded ?l2)))`

But, I obtained stranges results:
```
- Solution found in 1 steps!
1. move npc town castle

```
The expected result was:
```
- Solution found in 2 steps!
1. move npc town field
2. move npc field castle
```

I fork your project and I put my change in a directory "[mymagicworld](https://github.com/Tushn/strips/tree/master/examples/mymagicworld)"

Forgive me the inconvenience and thanks for any help!

**Comment by primaryobjects** [comment]
There is a STRIPS tutorial available that goes over some of these concepts [here](http://www.primaryobjects.com/2015/11/06/artificial-intelligence-planning-with-strips-a-gentle-introduction/). I hope this helps, thanks you.
